import type { Metadata } from "next";
import { poppins } from "@/lib/fonts";
import "@/styles/globals.css";
import "@/styles/app.css";
import Footer from "@/components/footer/Footer";
import LetsTalk from "@/components/letsTalk/LetsTalkHome";
import ParallaxContainer from "@/components/animations/HoverParallax";
import ContactPin from "@/components/hero/ContactPin";
import Navbar from "@/components/navigation/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins bg-white min-h-screen text-neutral-700 relative`}
      >
        <Navbar />
        {children}
        <LetsTalk />
        <Footer />
        <ParallaxContainer
          containerClassName="fixed bottom-10 right-10 z-50"
          scaleAmount={1.5}
        >
          <ContactPin />
        </ParallaxContainer>
      </body>
    </html>
  );
};

export default RootLayout;
