import type { Metadata } from "next";
import "@/styles/globals.css";
import { poppins } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins bg-slate-50 min-h-screen text-neutral-700`}
      >
        {children}
      </body>
    </html>
  );
}
